### ISSUE TITLE
How to run CaptchaFox on localhost domain? We don't want to use Tunnels etc.

### ISSUE THREAD

**Issue by zharonar** [CaptchaFox/javascript-integrations#42]
Hi,

We've implemented CaptchaFox, but we didn't find a solution how it could be used on localhost environment.

We found temporary solution via tunneling, where we add tunnel domain to the allowed domains, but this is not the way we want this to work. 

Is there an alternative settings?

**Comment by tgrassl** [comment]
Hi, one way is to use a custom local domain that maps to your localhost ip (e.g. dev.local). This can be added in the /etc/hosts file of your os. 
Another way is to use a testing key for the local environment: [https://docs.captchafox.com/automated-testing](https://docs.captchafox.com/automated-testing)
