### ISSUE TITLE
[Bug?]: SolidJS integration showing 2 captchas in form using a single CaptchaFox component

### ISSUE THREAD

**Issue by caseybaggz** [CaptchaFox/javascript-integrations#49]
## Context

Fox-package: solid
Stack: Solid-Start & Vercel

*This issue only seems to happen in our production site. Local development seems to work correctly?*

## Problem

Instead of showing a single Captcha box in a form, Fox displays two captcha's stacked on the form randomly.

### Steps to reproduce

1. Go to [our website](https://nurl.website)
2. Click the "contact" link in the main nav
3. 👀 Notice only a single Captcha in form
4. Click the "Sanctum" link in the main nav
5. Scroll down to the bottom, final CTA, and click button link
6. 🔴 Notice 2 captcha's in form
7. Refresh page
8. 👀 Notice 1 captcha in form

The good news is that even with the 2, the user only needs to verify once - but it is still confusing

It seems to only happen if you are on a form that uses a nested route path...which is odd?

## What I expect to happen

The CaptchaFox component should only render a single box no matter how the user navigates to the page.

**Comment by tgrassl** [comment]
Hi @caseybaggz, thanks for reporting! It looks like the container element does not destroy the element correctly during this route navigation.
Is it correct that you don't experience this issue on your local build?

**Comment by tgrassl** [comment]
Update: Can reproduce it locally using the solid example. We will get a fix released this week 👍

**Comment by caseybaggz** [comment]
@tgrassl Thanks for the quick response and yes - this only happens on our prod site. Locally works fine
